services:
  development:
    image: development:test
    build:
      context: .
      network: host
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
    user: build
    stdin_open: true
    tty: true
    network_mode: host
    working_dir: ${PWD}
    configs:
      - source: passwd
        target: /etc/passwd
      - source: group
        target: /etc/group
      - source: shadow
        target: /etc/shadow
    volumes:
      - type: bind
        source: ${PWD}
        target: ${PWD}
        bind:
          create_host_path: false
      - type: bind
        source: ${DOCKER_HISTORY:-${HOME}/.docker_history}
        target: /home/build/.bash_history
        bind:
          create_host_path: false

configs:
  passwd:
    content: |
      build::${DOCKER_UID:-1000}:${DOCKER_GID:-1000}::/home/build:/usr/bin/bash
  group:
    content: |
      build::${DOCKER_GID:-1000}:
  shadow:
    content: "#empty"
